# Generated by Django 5.2.9 on 2025-12-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0007_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
