# Generated by Django 5.2.9 on 2026-01-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0002_user_profile_picture_message_post_comment_and_more"),
        ("custom_account", "0008_alter_cv_id_alter_user_first_name_alter_user_id"),
    ]

    operations = []
