# Generated by Django 4.2.27 on 2026-01-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0010_auto_20260116_1723"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="event_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("photo", "Photo"),
                    ("video", "Video"),
                    ("event", "Event"),
                    ("article", "Article"),
                ],
                default="photo",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
