from django.urls import path
from jobapp import views

app_name = "jobapp"


urlpatterns = [

    path('', views.home_view, name='home'),
    path('jobs/', views.job_list_View, name='job-list'),
    path('job/create/', views.create_job_View, name='create-job'),
    path('job/<int:id>/', views.single_job_view, name='single-job'),
    path('apply-job/<int:id>/', views.apply_job_view, name='apply-job'),
    path('bookmark-job/<int:id>/', views.job_bookmark_view, name='bookmark-job'),
    path('about/', views.about_us_view, name='about'),
    path('contact/', views.contact_us_view, name='contact'),
    path('result/', views.search_result_view, name='search_result'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('employer-jobs-table/', views.employer_jobs_table_view, name='employer-jobs-table'),
    path('dashboard/employer/job/<int:id>/applicants/', views.all_applicants_view, name='applicants'),
    path('dashboard/employer/job/<int:job_id>/select-candidates/', views.select_candidates_view, name='select-candidates'),
    path('interview-session/<str:session_id>/', views.interview_session_view, name='interview-session'),
    path('dashboard/employer/job/edit/<int:id>', views.job_edit_view, name='edit-job'),
    path('dashboard/employer/applicant/<int:user_id>/<int:job_id>/', views.applicant_details_view, name='applicant-details'),
    path('dashboard/employer/close/<int:id>/', views.make_complete_job_view, name='complete'),
    path('dashboard/employer/publish/<int:id>/', views.publish_job_view, name='publish'),
    path('dashboard/employer/delete/<int:id>/', views.delete_job_view, name='delete'),
    path('dashboard/employee/delete-bookmark/<int:id>/', views.delete_bookmark_view, name='delete-bookmark'),
    path('student-dashboard', views.student_dashboard_view,name='student-dashboard'),
    path('student-exam', views.student_exam_view,name='student-exam'),
    path('take-exam/<int:pk>', views.take_exam_view,name='take-exam'),
    path('start-exam/<int:pk>', views.start_exam_view,name='start-exam'),
    path('calculate-marks', views.calculate_marks_view,name='calculate-marks'),
    path('view-result', views.view_result_view,name='view-result'),
    path('check-marks/<int:pk>', views.check_marks_view,name='check-marks'),
    path('applicant-marks', views.student_marks_view,name='student-marks'),
    path('teacher-dashboard', views.teacher_dashboard_view,name='teacher-dashboard'),
    path('teacher-exam', views.teacher_exam_view,name='teacher-exam'),
    path('teacher-add-exam', views.teacher_add_exam_view,name='teacher-add-exam'),
    path('teacher-view-exam', views.teacher_view_exam_view,name='teacher-view-exam'),
    path('delete-exam/<int:pk>', views.delete_exam_view,name='delete-exam'),
    path('teacher-question', views.teacher_question_view,name='teacher-question'),
    path('teacher-add-question', views.teacher_add_question_view,name='teacher-add-question'),
    path('teacher-view-question', views.teacher_view_question_view,name='teacher-view-question'),
    path('see-question/<int:pk>', views.see_question_view,name='see-question'),
    path('remove-question/<int:pk>', views.remove_question_view,name='remove-question'),

    # Custom Admin Panel
    path('admin-dashboard/', views.admin_dashboard_view, name='admin-dashboard'),
    path('admin-users/', views.admin_users_view, name='admin-users'),
    path('admin-users/create/', views.admin_user_create_view, name='admin-user-create'),
    path('admin-users/edit/<int:pk>/', views.admin_user_edit_view, name='admin-user-edit'),
    path('admin-users/delete/<int:pk>/', views.admin_user_delete_view, name='admin-user-delete'),
    path('admin-jobs/', views.admin_jobs_view, name='admin-jobs'),
    path('admin-jobs/create/', views.admin_job_create_view, name='admin-job-create'),
    path('admin-jobs/edit/<int:pk>/', views.admin_job_edit_view, name='admin-job-edit'),
    path('admin-jobs/publish/<int:pk>/', views.admin_job_publish_view, name='admin-job-publish'),
    path('admin-jobs/close/<int:pk>/', views.admin_job_close_view, name='admin-job-close'),
    path('admin-jobs/delete/<int:pk>/', views.admin_job_delete_view, name='admin-job-delete'),
    path('admin-applicants/', views.admin_applicants_view, name='admin-applicants'),
    path('admin-applicants/create/', views.admin_applicant_create_view, name='admin-applicant-create'),
    path('admin-applicants/edit/<int:pk>/', views.admin_applicant_edit_view, name='admin-applicant-edit'),
    path('admin-applicants/delete/<int:pk>/', views.admin_applicant_delete_view, name='admin-applicant-delete'),
    path('admin-categories/', views.admin_categories_view, name='admin-categories'),
    path('admin-categories/create/', views.admin_category_create_view, name='admin-category-create'),
    path('admin-categories/edit/<int:pk>/', views.admin_category_edit_view, name='admin-category-edit'),
    path('admin-categories/delete/<int:pk>/', views.admin_category_delete_view, name='admin-category-delete'),
    path('admin-students/', views.admin_students_view, name='admin-students'),
    path('admin-students/create/', views.admin_student_create_view, name='admin-student-create'),
    path('admin-students/edit/<int:pk>/', views.admin_student_edit_view, name='admin-student-edit'),
    path('admin-students/delete/<int:pk>/', views.admin_student_delete_view, name='admin-student-delete'),
    path('admin-teachers/', views.admin_teachers_view, name='admin-teachers'),
    path('admin-teachers/create/', views.admin_teacher_create_view, name='admin-teacher-create'),
    path('admin-teachers/edit/<int:pk>/', views.admin_teacher_edit_view, name='admin-teacher-edit'),
    path('admin-teachers/delete/<int:pk>/', views.admin_teacher_delete_view, name='admin-teacher-delete'),
    path('admin-courses/', views.admin_courses_view, name='admin-courses'),
    path('admin-courses/create/', views.admin_course_create_view, name='admin-course-create'),
    path('admin-courses/edit/<int:pk>/', views.admin_course_edit_view, name='admin-course-edit'),
    path('admin-courses/delete/<int:pk>/', views.admin_course_delete_view, name='admin-course-delete'),
    path('admin-questions/', views.admin_questions_view, name='admin-questions'),
    path('admin-questions/create/', views.admin_question_create_view, name='admin-question-create'),
    path('admin-questions/edit/<int:pk>/', views.admin_question_edit_view, name='admin-question-edit'),
    path('admin-questions/delete/<int:pk>/', views.admin_question_delete_view, name='admin-question-delete'),
    path('admin-results/', views.admin_results_view, name='admin-results'),
    path('admin-results/create/', views.admin_result_create_view, name='admin-result-create'),
    path('admin-results/edit/<int:pk>/', views.admin_result_edit_view, name='admin-result-edit'),
    path('admin-results/delete/<int:pk>/', views.admin_result_delete_view, name='admin-result-delete'),
    path('admin-bookmarks/', views.admin_bookmarks_view, name='admin-bookmarks'),
    path('admin-bookmarks/create/', views.admin_bookmark_create_view, name='admin-bookmark-create'),
    path('admin-bookmarks/edit/<int:pk>/', views.admin_bookmark_edit_view, name='admin-bookmark-edit'),
    path('admin-bookmarks/delete/<int:pk>/', views.admin_bookmark_delete_view, name='admin-bookmark-delete'),
    path('admin-user-visits/', views.admin_user_visits_view, name='admin-user-visits'),
    
    # Company Info Pages
    path('company-about/', views.company_about_view, name='company-about'),
    path('careers/', views.career_view, name='careers'),
    path('blog/', views.blog_view, name='blog'),
    path('resources/', views.resources_view, name='resources'),
    path('privacy-policy/', views.privacy_view, name='privacy'),
    path('terms-of-service/', views.terms_view, name='terms'),

]
