# Generated by Django 3.0 on 2020-04-27 08:45

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_auto_20200427_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_des',
            field=CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='des',
            field=CKEditor5Field(blank=True, null=True),
        ),
    ]
