# Generated by Django 3.0 on 2020-04-27 09:35

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_job_company_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_des',
        ),
        migrations.RemoveField(
            model_name='job',
            name='des',
        ),
        migrations.AlterField(
            model_name='job',
            name='company_description',
            field=CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=CKEditor5Field(),
        ),
    ]
