# Generated by Django 3.0 on 2020-04-27 09:37

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_auto_20200427_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_description',
            field=CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=CKEditor5Field(),
        ),
    ]
