# Generated by Django 5.2.9 on 2025-12-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0028_alter_applicant_id_alter_bookmarkjob_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
