# Generated by Django 5.2.9 on 2026-01-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0029_applicant_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="marks_per_question",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
