# Generated by Django 3.2.25 on 2026-01-16 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapp', '0030_course_marks_per_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('round1', 'Round 1 - Resume & Quiz'), ('round2', 'Round 2 - Live Interview')], default='round1', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0.0)),
                ('selected_for_next_round', models.BooleanField(default=False)),
                ('salary_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.applicant')),
                ('interview_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.interviewround')),
            ],
            options={
                'unique_together': {('interview_round', 'applicant')},
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('scheduled_at', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('final_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview_selection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobapp.interviewselection')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interviewround',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job'),
        ),
    ]
